# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 180)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 131, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_loadImg2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_loadImg2.setGeometry(QtCore.QRect(10, 60, 111, 25))
        self.btn_loadImg2.setObjectName("btn_loadImg2")
        self.btn_loadImg1 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_loadImg1.setGeometry(QtCore.QRect(10, 20, 111, 25))
        self.btn_loadImg1.setObjectName("btn_loadImg1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(150, 30, 151, 101))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_matchKeyPts = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_matchKeyPts.setGeometry(QtCore.QRect(10, 60, 131, 25))
        self.btn_matchKeyPts.setObjectName("btn_matchKeyPts")
        self.btn_keypts = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_keypts.setGeometry(QtCore.QRect(10, 20, 131, 25))
        self.btn_keypts.setObjectName("btn_keypts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "4. SIFT"))
        self.btn_loadImg2.setText(_translate("MainWindow", "Load Image 2"))
        self.btn_loadImg1.setText(_translate("MainWindow", "Load Image 1"))
        self.btn_matchKeyPts.setText(_translate("MainWindow", "4.2 Matched Keypoints"))
        self.btn_keypts.setText(_translate("MainWindow", "4.1 Keypoints"))
