# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 401))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_loadImg = QtWidgets.QPushButton(self.groupBox)
        self.btn_loadImg.setGeometry(QtCore.QRect(20, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_loadImg.setFont(font)
        self.btn_loadImg.setObjectName("btn_loadImg")
        self.btn_inference = QtWidgets.QPushButton(self.groupBox)
        self.btn_inference.setGeometry(QtCore.QRect(20, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_inference.setFont(font)
        self.btn_inference.setObjectName("btn_inference")
        self.btn_showCompare = QtWidgets.QPushButton(self.groupBox)
        self.btn_showCompare.setGeometry(QtCore.QRect(20, 280, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_showCompare.setFont(font)
        self.btn_showCompare.setObjectName("btn_showCompare")
        self.btn_showMdlStruc = QtWidgets.QPushButton(self.groupBox)
        self.btn_showMdlStruc.setGeometry(QtCore.QRect(20, 220, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_showMdlStruc.setFont(font)
        self.btn_showMdlStruc.setObjectName("btn_showMdlStruc")
        self.btn_showImg = QtWidgets.QPushButton(self.groupBox)
        self.btn_showImg.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_showImg.setFont(font)
        self.btn_showImg.setObjectName("btn_showImg")
        self.btn_showDtrb = QtWidgets.QPushButton(self.groupBox)
        self.btn_showDtrb.setGeometry(QtCore.QRect(20, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_showDtrb.setFont(font)
        self.btn_showDtrb.setObjectName("btn_showDtrb")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 80, 231, 241))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_prediction = QtWidgets.QLabel(self.centralwidget)
        self.lbl_prediction.setGeometry(QtCore.QRect(280, 330, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_prediction.setFont(font)
        self.lbl_prediction.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_prediction.setObjectName("lbl_prediction")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 615, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 CvDl Hw2-5"))
        self.groupBox.setTitle(_translate("MainWindow", "5. ResNet50"))
        self.btn_loadImg.setText(_translate("MainWindow", "Load Image"))
        self.btn_inference.setText(_translate("MainWindow", "5. Inference"))
        self.btn_showCompare.setText(_translate("MainWindow", "4. Show Comparison"))
        self.btn_showMdlStruc.setText(_translate("MainWindow", "3. Show Model Structure"))
        self.btn_showImg.setText(_translate("MainWindow", "1. Show Images"))
        self.btn_showDtrb.setText(_translate("MainWindow", "2. Show Distribution"))
        self.lbl_prediction.setText(_translate("MainWindow", "Prediction: "))
